# Generated by Django 5.2.8 on 2025-11-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, '1 period'), (2, '2 period'), (3, '3 period'), (4, '4 period')], null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='week',
            field=models.IntegerField(blank=True, choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5'), (6, 'Week 6'), (7, 'Week 7'), (8, 'Week 8'), (9, 'Week 9')], null=True),
        ),
    ]
