# Generated by Django 5.2.8 on 2025-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_period_project_source_url_project_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')])),
                ('notify', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
