# Generated by Django 5.2.8 on 2025-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
