# Generated by Django 5.2.8 on 2025-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comment_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='uploads/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
