# Generated by Django 5.2.8 on 2025-12-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_comment_email_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('CLOSE', 'close')], default='approved'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('SUBMITTED', 'submitted')], default='approved'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
